force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <label>Appointment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Appointment_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Time__c</fullName>
    <label>Appointment Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Dentist__c.field-meta.xml
<CustomField>
    <fullName>Dentist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dentist</label>
    <referenceTo>Dentist__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <label>Patient Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dentist__c/Dentist__c.object-meta.xml
<CustomObject>
    <label>Dentist</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dentists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ReportController.cls
/**
 * @description       : 
 * @author            : Nazar Voinarovych
 * @group             : 
 * @last modified on  : 11-27-2024
 * @last modified by  : Nazar Voinarovych
**/
public with sharing class ReportController {

    public List<Appointment__c> todayAppointments {get;set;}

    public ReportController(){
        getAppointmentsWithTodayDate();
    }

    @AuraEnabled(cacheable=true)
    public static Id getReportByName(String reportName){
        Report report= [SELECT Id,Name FROM Report WHERE Name=:reportName];
        return report.Id;
    }

    @AuraEnabled(cacheable=true)
    public void getAppointmentsWithTodayDate(){
        todayAppointments= [
            SELECT Id,
            Appointment_Time__c,
            Appointment_Date__c,
            Dentist__r.Name,
            Patient_Name__c,
            Status__c
            FROM Appointment__c
            WHERE Appointment_Date__c=:Date.today()
            WITH SECURITY_ENFORCED
            ORDER BY Appointment_Time__c
            ];   
    }
}